envname: HumanoidNavigateEnv
model_id: r1Q1Z4BcV1o
target_orn: [0, 0, 1.57]
target_pos: [-14.3, 45.07, 0.5]
initial_orn: [0, 0, 1.87]
initial_pos: [-3.3, -2.80, 0.9]
#initial_pos: [-8.2, 6.00, 0.9]
fov: 1.57
is_discrete: false

use_filler: true
display_ui: true
show_diagnostics: False
ui_num: 3
ui_num: 6
ui_components: [RGB_FILLED, DEPTH, MAP, SEMANTICS, NORMAL, PHYSICS]
#ui_components: [PHYSICS]
#ui_components: [PHYSICS, MAP, RGB_FILLED]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor, rgb_filled, depth, map, normal, physics, semantics]
#output: [nonviz_sensor]
#output: [nonviz_sensor, map, rgb_filled]
resolution: 512
#resolution: 512

speed:
  timestep: 0.001
  frameskip: 10

mode: gui #gui|headless
verbose: false
#fast_lq_render: true

semantic_source: 2 # Matterport 3D
semantic_color: 1
enable_ui_recording: false

#no_semantis: True
start_record: True