envname: HuskyNavigateEnv
model_id: r1Q1Z4BcV1o
target_orn: [0, 0, 1.57]
target_pos: [-14.3, 45.07, 0.5]
initial_orn: [0, 0, 1.6]
#initial_pos: [1.18, 2.70, 0.2]
initial_pos: [-9.2, -2.00, 1.0]
fov: 1.57
is_discrete: true

use_filler: true
display_ui: true
show_diagnostics: False
#ui_num: 3
ui_num: 6
ui_components: [RGB_FILLED, DEPTH, MAP, SEMANTICS, NORMAL, PHYSICS]
#ui_components: [PHYSICS, MAP, NORMAL]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor, rgb_filled, depth, map, semantics, normal, physics]
#output: [physics, map, normal]
resolution: 512
#resolution: 512

speed:
  timestep: 0.001
  frameskip: 10

mode: gui #gui|headless
verbose: false
#fast_lq_render: true

semantic_source: 2 # Matterport 3D
semantic_color: 2
enable_ui_recording: true